[package]
name = "tower-hyper"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
http = "0.1"
hyper = { version = "0.12", path = "../hyper" }
log = "0.4"
tokio-io = "0.1"
tower-service = { path = "../tower/tower-service" }
tower-direct-service = { path = "../tower/tower-direct-service" }
tower-util = { path = "../tower/tower-util" }

[dev-dependencies]
tower-buffer = { path = "../tower/tower-buffer" }
pretty_env_logger = "0.2.0"